$script = <<END
sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
apt-get install -y postgresql-9.6
apt-get install -y postgresql-contrib-9.6
systemctl start postgresql.service
systemctl enable postgresql.service
apt -y install python3
apt -y install python3-pip
apt -y install libpq-dev
python3 -m pip install psycopg2-binary
python3 -m pip install Django
END

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.provision "shell", inline: $script
  config.vm.provision "file", source: "~/some_code", destination: "some_code"  
end
